"""empty message

Revision ID: 0c2b3c064586
Revises: 6cde1805b5cf
Create Date: 2024-12-14 10:15:29.288025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2b3c064586'
down_revision = '6cde1805b5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_centre', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_column('health_centre')

    # ### end Alembic commands ###
