"""empty message

Revision ID: 18e92ff04324
Revises: c5f4d38f45a5
Create Date: 2024-12-20 13:51:08.076699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e92ff04324'
down_revision = 'c5f4d38f45a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('rdf_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_session', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('rdf_file')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
