"""empty message

Revision ID: 279c92b3b95b
Revises: ecc76e29a09c
Create Date: 2024-11-13 03:04:52.923074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279c92b3b95b'
down_revision = 'ecc76e29a09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practitioner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practitioner', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
