"""empty message

Revision ID: 31325498cfe0
Revises: 7daeb889ffa2
Create Date: 2025-03-14 14:54:17.567375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31325498cfe0'
down_revision = '7daeb889ffa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.alter_column('public_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('private_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.alter_column('private_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('public_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
