"""empty message

Revision ID: 37b664e9c053
Revises: 88ba77200539
Create Date: 2025-03-03 15:34:46.362590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b664e9c053'
down_revision = '88ba77200539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('practitioner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practitioner', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('address')
        batch_op.drop_column('birthday')
        batch_op.drop_column('gender')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('birthday')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
