"""empty message

Revision ID: 48dfd9f500b2
Revises: 18e92ff04324
Create Date: 2025-01-06 11:00:59.918961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dfd9f500b2'
down_revision = '18e92ff04324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_application_data')
    op.drop_table('organization')
    with op.batch_alter_table('application_data', schema=None) as batch_op:
        batch_op.drop_column('fitbit_refresh_time')

    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_column('patientEHR_id')
        batch_op.drop_column('practitionerEHR_id')
        batch_op.drop_column('patient_email')
        batch_op.drop_column('health_centre')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    with op.batch_alter_table('practitioner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practitioner', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_centre', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('patient_email', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('practitionerEHR_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('patientEHR_id', sa.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('application_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitbit_refresh_time', sa.DATETIME(), nullable=False))

    op.create_table('organization',
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('_alembic_tmp_application_data',
    sa.Column('application_data_id', sa.INTEGER(), nullable=False),
    sa.Column('fitbit_client_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('fitbit_secret', sa.VARCHAR(length=255), nullable=False),
    sa.Column('fhir_server_url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('application_data_id')
    )
    # ### end Alembic commands ###
