"""empty message

Revision ID: 7daeb889ffa2
Revises: a4fbeee4d136
Create Date: 2025-03-14 00:00:42.038054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daeb889ffa2'
down_revision = 'a4fbeee4d136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###
