"""empty message

Revision ID: 88ba77200539
Revises: a3869abcbf05
Create Date: 2025-01-06 20:27:13.291765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ba77200539'
down_revision = 'a3869abcbf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.drop_column('request_data_type')
        batch_op.drop_column('destination_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('request_data_type', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
