"""empty message

Revision ID: a4fbeee4d136
Revises: 37b664e9c053
Create Date: 2025-03-13 23:47:29.899102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fbeee4d136'
down_revision = '37b664e9c053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.String(length=255), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###
